// frontend-svelte/src/lib/vistas/Principal.svelte
<script>
    import DialogoLogin from "../componentes/DialogoLogin.svelte";
    import Logout from "../componentes/Logout.svelte";
</script>

<h2>Página principal</h2>

<Logout/>
<DialogoLogin rutaDestino="privado"/>

<p>Esta es la página de inicio de la aplicación.</p>
<p>Este contenido es de acceso público.</p>

// frontend-react/src/vistas/Principal.jsx
import DialogoLogin from "../componentes/DialogoLogin"
import Logout from "../componentes/Logout"

function Principal() {

    return(
        <>
        <h2>Ola!</h2>
        <DialogoLogin rutaDestino="/privado/"/>
        <Logout/>
        <p>Esta é a páxina princial desta aplicación de probas de autorización con React.</p>
        <p>Esta páxina é pública e podese ver sen iniciar sesión</p>
        </>
    )
}

export default Principal
