// frontend/src/componentes/PerfilUsuario.jsx
import { useState, useContext } from "react"
import { aDataURL } from "../lib/ficheros.mjs"
import { enviarPerfil } from "../lib/fetch.jsx"
import { contextoAutorizacion } from "../servicios/Autorizacion.jsx"
import style from "./PerfilUsuario.module.css"

function PerfilUsuario() {

    const { paseAutorizacion } = useContext(contextoAutorizacion)

    const [ nome, setNome ] = useState("")
    const [ telefono, setTelefono ] = useState("")
    const [ correoElectronico, setCorreoElectronico ] = useState("")
    const [ fichero, setFichero ] = useState()

    function manexadorNome(evento) {
        setNome(evento.target.value)
    }
    function manexadorTelefono(evento) {
        setTelefono(evento.target.value)
    }
    function manexadorCorreo(evento) {
        setCorreoElectronico(evento.target.value)
    }
    function manexadorFichero(evento) {
        const fichero = evento.target.files[0]
        aDataURL(fichero, setFichero)
    }
    function manexadorEnviar() {
        const perfil = {
            nome,
            telefono,
            correoElectronico,
            fichero
        }
        enviarPerfil(perfil, paseAutorizacion, manejadorEnvio)
    }
    function manejadorEnvio(datos) {
        if ( datos === false ) alert("No ha sido posible guardar el perfil")
    }

    return (
        <div className={style.centrado+" "+style.contenedor}>
            <div className={style.contenedor}>
                <img className={style.imagen} src={fichero} alt="Imagen de perfil." />
                <label>
                    Nombre
                    <input className={style.bloque} type="text" value={nome} onInput={manexadorNome}/>
                </label>
                <label>
                    Teléfono
                    <input className={style.bloque} type="tel" value={telefono} onInput={manexadorTelefono}/>
                </label>
                <label>
                    Correo
                    <input className={style.bloque} type="email" value={correoElectronico} onInput={manexadorCorreo}/>
                </label>
                <label>
                    Imagen de perfil
                    <input className={style.bloque} type="file" onInput={manexadorFichero}/>
                </label>
                <button onClick={manexadorEnviar}>Guardar</button>
            </div>
        </div>
    )
}

export default PerfilUsuario

// frontend-svelte/src/lib/componentes/PerfilUsuario.svelte
<script>

    import { aDataURL } from "./../ficheros.mjs"
    import { enviarPerfil, recuperarPerfil } from "../fetch.mjs";
    import { paseAutorizacion } from "../servicios/servizoAutorizacion.mjs";
    import { onMount } from "svelte";

    let fichero, nome, telefono, correoElectronico

    async function manexadorFichero(evento) {
        const ficheroSeleccionado = evento.target.files[0]
        fichero = await aDataURL(ficheroSeleccionado)
    }

    function manexadorEnviar() {
        const perfil = {
            nome,
            telefono,
            correoElectronico,
            fichero
        }
        enviarPerfil(perfil, $paseAutorizacion, manejadorResultadoEnvio)
    }

    function manejadorResultadoEnvio(datos) {
        if ( datos === false ) alert("No ha sido posible guardar el perfil")
    }

    function obtenerDatosPerfil(){
        recuperarPerfil($paseAutorizacion, rellenarDatosPerfil)
    }

    function rellenarDatosPerfil(datosPerfil) {
        if (datosPerfil) {
            nome = datosPerfil.nome
            telefono = datosPerfil.telefono
            correoElectronico = datosPerfil.correoElectronico
            fichero = datosPerfil.fotoDePerfil.datos
        }
    }

    onMount(obtenerDatosPerfil)

</script>

<div class="centrado contenedor">
    <div class="contenedor">
        <img class="imagen" src={fichero} alt="Imagen de perfil." />
        <label>
            Nombre
            <input class="bloque" type="text" value={nome}/>
        </label>
        <label>
            Teléfono
            <input class="bloque" type="tel" value={telefono}/>
        </label>
        <label>
            Correo
            <input class="bloque" type="email" value={correoElectronico}/>
        </label>
        <label>
            Imagen de perfil
            <input class="bloque" type="file" on:input={manexadorFichero}/>
        </label>
        <button on:click={manexadorEnviar}>Guardar</button>
    </div>
</div>

<style>
.contenedor {
    position: relative;
}

.bloque {
    display: block;
}

.centrado {
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    align-content: center;
}

.imagen{
    position: absolute;
    top: 0px;
    right: 0px;
    max-width: 70px;
    max-height: 70px;
    z-index: -1;
}
</style>
