// frontend-svelte/src/App.svelte
<script>
    import { Router, Link, Route } from "svelte-routing";
    import Principal from "./lib/vistas/Principal.svelte";
    import Privada from "./lib/vistas/Privada.svelte";
</script>

<h1>Autorización en Svelte</h1>
<Router>
  <nav>
    <Link to="/">Inicio</Link>
    <Link to="privado">Área privada</Link>
  </nav>
  <main>
    <Route path="">
      <Principal/>
    </Route>
    <Route path="privado">
      <Privada/>
    </Route>
  </main>
</Router>

<style>
</style>

// frontend-react/src/App.js
import { BrowserRouter, Routes, Route, Link } from "react-router-dom";

import Principal from "./vistas/Principal";
import Privado from "./vistas/Privado";
import { ProveedorAutorizacion } from "./servicios/Autorizacion";

function App() {
  return (
    <ProveedorAutorizacion>
      <h1>Exemplo autorizacion con React</h1>
      <BrowserRouter>
      <nav>
        <ul>
          <Link to="/"><li>Inicio</li></Link> 
          <Link to="/privado/"><li>Privado</li></Link>
        </ul>
      </nav>
      <main>
        <Routes>
          <Route path="/" element={<Principal/>}/>
          <Route path="/privado/" element={<Privado/>}/>
        </Routes>
      </main>
      </BrowserRouter>
    </ProveedorAutorizacion>
  );
}

export default App;
